name: ai_flutter_gomoku
description: AI Flutter Gomoku Game

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2 # 本地数据存储
  http: ^1.1.0 # 网络请求
  flutter_riverpod: ^2.4.9 # 状态管理
  go_router: ^13.0.0 # 路由管理
  cupertino_icons: ^1.0.2 # 添加这行，包含了 Material Icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true # 这行很重要，启用 Material Icons


